version: "3.7"
services:
  postgres_db:
    image: postgres:10
    container_name: "postgres_db"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=projeto
      - POSTGRES_PASSWORD=projeto
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5433:5432
  seguradora-api:
    image: seguradora-api
    ports:
    - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/postgres
      SPRING_DATASOURCE_USERNAME: "projeto"
      SPRING_DATASOURCE_PASSWORD: "projeto"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - postgres_db
